### ISSUE TITLE
勝手に"もっと見る"を開く

### ISSUE THREAD

**Issue by 1129** [webken/bukuma-diver#7]
ホットエントリーの初期表示見出しの記事をクリックしたら、そのカテゴリの"もっと見る"を勝手に開き、残りの人気記事を表示。
見出しをクリックしたらそのカテゴリに興味があるということなので、そのカテゴリの表示件数が増えることで、興味を引く記事をより多く表示されるはず。
そうしてズルズルとネットサーフィンを続けさせる。

**Comment by en30** [comment]
ナイスアイデア
![寿司ゆき:sparkles](https://d1zd1v0cxnbx2w.cloudfront.net/images/sets/sushiyuki/31.png)
